project:
  type: website

website:
  title: "Wellcome NIHR SPCR Primary care clinician doctoral project"
  navbar:
    right:
      - icon: github
        text: GitHub
        href: https://github.com/pythonhealthdatascience/quarto-template/
  sidebar:
    - logo: images/exeter.png
      contents:
        - text: Overview
          href: index.qmd
        - pages/Systematic review.qmd
        - pages/CPRD Study 1.qmd
        - pages/CPRD Study 2.qmd
        - pages/Focus group and Delphi consensus.qmd
        - pages/Contact us.qmd

format:
  html:
    theme: flatly